apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: myproject
spec:
  containers:
  - name: kafka
    image: strimzi/kafka:0.16.2-kafka-2.4.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"

