apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-nfs-storage
provisioner: my-nfs-provisioner
parameters:
  archiveOnDelete: "false"  # When set to "false" your PVs will not be archived
                           # by the provisioner upon deletion of the PVC.
